name: Build and deploy Node.js app to Azure Web App - GalleryAzureBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm install

      - name: Prepare deployment package
        run: |
          zip -r release.zip server.js db.js package.json package-lock.json client-dist

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
     run: unzip release.zip -d .


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3220FD3C0F949DF939F732A5B5835BB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_096F17E9980345178682D1D9EDB7EF3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3B09377C9EFA46E1A660B1A38B974DBD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GalleryAzureBackend'
          slot-name: 'Production'
          package: .
